---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - ln -s ansible-role-nginx ../Aplyca.Nginx

install:
  # Install Ansible.
  - sudo pip install -r tests/requirements.txt

addons:
  hosts:
    - myapp.com

script:
  - tests/tests.sh

notifications:
  email: false
