---
- name: reload nginx
  sudo: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: restart nginx
  sudo: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

